//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabletShop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TabletShop.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your order! Your order number is:.
        /// </summary>
        public static string lblThanksForYourOrderYourOrderNumberIs {
            get {
                return ResourceManager.GetString("lblThanksForYourOrderYourOrderNumberIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your cart:.
        /// </summary>
        public static string lblYourCart {
            get {
                return ResourceManager.GetString("lblYourCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string signDollar {
            get {
                return ResourceManager.GetString("signDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address And Payment.
        /// </summary>
        public static string txtAddressAndPayment {
            get {
                return ResourceManager.GetString("txtAddressAndPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Complete.
        /// </summary>
        public static string txtCheckoutComplete {
            get {
                return ResourceManager.GetString("txtCheckoutComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetImage?image={0}.
        /// </summary>
        public static string txtGetImage {
            get {
                return ResourceManager.GetString("txtGetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string txtID {
            get {
                return ResourceManager.GetString("txtID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string txtModel {
            get {
                return ResourceManager.GetString("txtModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string txtOrder {
            get {
                return ResourceManager.GetString("txtOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string txtPrice {
            get {
                return ResourceManager.GetString("txtPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string txtQuantity {
            get {
                return ResourceManager.GetString("txtQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from cart.
        /// </summary>
        public static string txtRemoveFromCard {
            get {
                return ResourceManager.GetString("txtRemoveFromCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string txtReview {
            get {
                return ResourceManager.GetString("txtReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablet.
        /// </summary>
        public static string txtTablet {
            get {
                return ResourceManager.GetString("txtTablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This web shop was developed by Maksym Mokrousov for trycath.us.
        /// </summary>
        public static string txtThisWebShopWsDeveloped {
            get {
                return ResourceManager.GetString("txtThisWebShopWsDeveloped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string txtTotal {
            get {
                return ResourceManager.GetString("txtTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You could return to tablet.
        /// </summary>
        public static string txtYouCouldReturnToTablet {
            get {
                return ResourceManager.GetString("txtYouCouldReturnToTablet", resourceCulture);
            }
        }
    }
}
